package bookStore;

import Pojos.createBooks;
import Pojos.signUp;

public class createBook {


    public  static createBooks setBooks(){
        return  createBooks
                .builder()
                .name("RestAssured")
                .author("Masood")
                .published_year(2019)
                .book_summary("Selenium with Java")
                .build();
    }
    public static createBooks createBookObject(int id,String name, String author, int publishedYear, String bookSummary) {
        // ID is often generated by the backend for new resources, so we might omit it here
        // or set it to 0/null and let the backend assign.
        return createBooks.builder()
                .id(id)
                .name(name)
                .author(author)
                .published_year(publishedYear)
                .book_summary(bookSummary)
                .build();
    }

}
